# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Builder using single stage
FROM node:lts-alpine
WORKDIR /app
# Copy source
COPY package.json tsconfig.json ./
COPY src ./src
# Install dependencies, build, and prune dev
RUN npm install --ignore-scripts && npm run build && npm prune --production
# Expose no port since stdio
ENTRYPOINT ["node", "dist/index.js"]
