# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Copy package files first for caching
COPY package.json tsconfig.json ./

# Copy source
COPY src ./src

# Install dependencies without running scripts, then build
RUN npm install --ignore-scripts && npm run build

# Default CMD (overridden by MCP startCommand execution)
CMD ["node", "dist/index.js"]
